language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI server home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r great-grade-points *
  - mkdir -p deploy
  - mv great-grade-points.zip deploy/great-grade-points.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ggp-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ggp-springboot-build
    key: great-grade-points.zip
    bundle_type: zip
    application: great-grade-points
    deployment_group: great-grade-points-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - likerdo@naver.com
