spring:
  jpa:
    show-sql: true
    properties:
      hibernate :
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  profiles:
    include: oauth
server:
  port: 9000